# Hydra config for training mano regressor

defaults:
  - _self_
  - data: h20_dino

task_name: "train_mano_regressor"

train: True

log_level: INFO

model:
  learning_rate: 1e-3
  sixd: True
  mano_params: 109

logger:
  name: "run_pretrained"
  save_dir: "./logs"
  group: "train_mano_regressor"
  log_model: True

trainer:
  log_every_n_steps: 50
  max_epochs: 200
  accelerator: "auto"
  devices: 1
