# Hydra config for training mano regressor

defaults:
  - _self_
  - data: h20_pretrained

task_name: "train_mano_regressor"

train: True

log_level: INFO

data:
  temporal_aug: True

model:
  learning_rate: 1e-3
  loss_weights:
    keypoints_3d: 0.05
    keypoints_2d: 0.01
    global_translation: 50
    global_orientation: 0.2
    pose: 0.2
    shape: 0.02
    keypoint_diversity: 1
    temporal_diversity: 1
  sixd: True
  mano_params: 109
  mean_mano_params_location: "/cluster/project/cvg/students/mzamboni/3D-hand-FM/external/mano_mean_params.npz"
  last_frame_only: False

transforms: null

logger:
  name: "run_pretrained"
  save_dir: "./logs"
  group: "train_mano_regressor"
  log_model: True

trainer:
  max_epochs: 200
  accelerator: "auto"
  devices: 4
