# Hydra config for training vae

defaults:
  - _self_
  - data: h20

task_name: "train_vae"

train: True

log_level: INFO

model:
  learning_rate: 1e-3
  kld_weight: 0.00025
  mse_weight: 1e-8

logger:
  name: "test_run"
  save_dir: "./logs"
  group: "train_vae"
  log_model: False # Don't log model weights

trainer:
  max_epochs: 20
  accelerator: "auto"
  devices: 1
